blank_issues_enabled: false
contact_links:
  - name: Report security issue
    url: https://github.com/debezium/dbz/security/advisories/new
    about: Please report all security and CVE issues here.
  - name: Debezium Community Support
    url: https://debezium.io/community/
    about: Please ask and answer questions here.
